[pytest]
pythonpath = .
testpaths = web/tests api/tests
bdd_features_base_dir = web/tests/features
markers =
    smoke: pruebas rápidas de humo
    regression: pruebas de regresión completas
addopts = -ra --html=reports/report.html --self-contained-html --alluredir=reports/allure-results
